version: '3'

services:
  svc3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 9002:9002
    networks:
      - traefik-net
    labels:
      - "traefik.http.routers.svc3.rule=Host(`server2.localhost`)"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true